### PR TITLE
feat: Move eslint plugins to peer dependencies.

### PR DESCRIPTION
**Pull request by yeldiRium**

### CODE REVIEW

**Review by goloroden — CHANGES_REQUESTED** [review]
Hey @yeldiRium 👋 

This change makes sense, however – it affects how to install the module (respectively how to set it up that it works correctly).

Shouldn't we add an appropriate notice in the documentation for that?

**Comment by yeldiRium** [comment]
> Hey @yeldiRium wave
> 
> This change makes sense, however – it affects how to install the module (respectively how to set it up that it works correctly).
> 
> Shouldn't we add an appropriate notice in the documentation for that?

It actually changes nothing in how this package is used, it just changes the layout of the dependencies in dependents. The way I understand peer dependencies, this change should be nonbreaking for our dependents.

**Comment by goloroden** [comment]
IIRC you have to manually install peer dependencies, don't you?

**Comment by yeldiRium** [comment]
No, peer dependencies are installed automatically. Only optional dependencies have to be installed manually.

**Comment by goloroden** [comment]
It was different with earlier versions of npm:

> npm versions 1, 2, and 7 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. For npm versions 3 through 6, you will receive a warning that the peerDependency is not installed instead.

So, for now it's fine 👍

We only need to fix the merge conflict.

**Review by goloroden — APPROVED** [review]

**Pull request merged**
